export enum ECities {
  VINNYTSA = "Vinnytsa",
  VOLYN = "Volyn",
  DNIPROPETROVS = "Dnipropetrovs",
  DONETSK = "Donetsk",
  ZHYTOMYR = "Zhytomyr",
  ZAKARPATYA = "Zakarpatska",
  ZAPORIZHA = "Zaporizha",
  IVANO_FRANKIVSK = "Ivano_Frankivsk",
  KYIV = "Kyiv",
  KIROVOHRAD = "Kirovohrad",
  LUHANSK = "Luhansk",
  LVIV = "Lviv",
  MYKOLAIV = "Mykolaiv",
  ODESA = "Odesa",
  POLTAVA = "Poltava",
  RIVNE = "Rivne",
  SUMU = "Sumu",
  TERNOPIL = "Ternopil",
  KHARKIV = "Kharkiv",
  KHERSON = "Kherson",
  KHMELNYTSK = "Khmelnytsk",
  CHERKASU = "Cherkasu",
  CHERNIVTSI = "Chernivtsi",
  CHERNIHIV = "Chernihiv",
}
